In [1]:
from nba_api.stats.endpoints import playercareerstats, draftcombinestats
import pandas as pd

In [3]:
data  = draftcombinestats.DraftCombineStats(league_id='00',season_all_time="2024-25")

pd_data = data.draft_combine_stats.get_data_frame()
pd_data.head()

,SEASON,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,HEIGHT_W_SHOES,HEIGHT_W_SHOES_FT_IN,...,SPOT_NBA_BREAK_RIGHT,SPOT_NBA_CORNER_RIGHT,OFF_DRIB_FIFTEEN_BREAK_LEFT,OFF_DRIB_FIFTEEN_TOP_KEY,OFF_DRIB_FIFTEEN_BREAK_RIGHT,OFF_DRIB_COLLEGE_BREAK_LEFT,OFF_DRIB_COLLEGE_TOP_KEY,OFF_DRIB_COLLEGE_BREAK_RIGHT,ON_MOVE_FIFTEEN,ON_MOVE_COLLEGE
0,2024,1642369,Michael,Ajayi,Michael Ajayi,SF,77.75,6' 5.75'',None,None,...,None,None,None,None,None,15-30,None,None,None,13-25
1,2024,1642351,Melvin,Ajinca,Melvin Ajinca,SF,79.25,6' 7.25'',None,None,...,None,None,None,None,None,NaN,None,None,None,NaN
2,2024,1641725,Trey,Alexander,Trey Alexander,SG,75.25,6' 3.25'',None,None,...,None,None,None,None,None,21-30,None,None,None,13-25
3,2024,1641891,Izan,Almansa,Izan Almansa,C,81.25,6' 9.25'',None,None,...,None,None,None,None,None,19-30,None,None,None,8-25
4,2024,1641736,Reece,Beekman,Reece Beekman,PG,73.25,6' 1.25'',None,None,...,None,None,None,None,None,22-30,None,None,None,16-25

In [4]:
missing = pd_data.isnull().sum()
missing_pct = (pd_data.isnull().sum() / len(pd_data)) * 100

# View as a summary
missing_df = pd.DataFrame({
    'column': pd_data.columns,
    'missing_count': missing.values,
    'missing_pct': missing_pct.values
}).sort_values('missing_pct', ascending=False)

print(missing_df)

                          column  missing_count  missing_pct
8                 HEIGHT_W_SHOES             83   100.000000
9           HEIGHT_W_SHOES_FT_IN             83   100.000000
34          SPOT_NBA_CORNER_LEFT             83   100.000000
35           SPOT_NBA_BREAK_LEFT             83   100.000000
36              SPOT_NBA_TOP_KEY             83   100.000000
37          SPOT_NBA_BREAK_RIGHT             83   100.000000
38         SPOT_NBA_CORNER_RIGHT             83   100.000000
23                   BENCH_PRESS             83   100.000000
24      SPOT_FIFTEEN_CORNER_LEFT             83   100.000000
25       SPOT_FIFTEEN_BREAK_LEFT             83   100.000000
26          SPOT_FIFTEEN_TOP_KEY             83   100.000000
27      SPOT_FIFTEEN_BREAK_RIGHT             83   100.000000
28     SPOT_FIFTEEN_CORNER_RIGHT             83   100.000000
30       SPOT_COLLEGE_BREAK_LEFT             83   100.000000
15                  BODY_FAT_PCT             83   100.000000
39   OFF_DRIB_FIFTEEN_BREAK_LEFT             83   100.000000
40      OFF_DRIB_FIFTEEN_TOP_KEY             83   100.000000
41  OFF_DRIB_FIFTEEN_BREAK_RIGHT             83   100.000000
43      OFF_DRIB_COLLEGE_TOP_KEY             83   100.000000
45               ON_MOVE_FIFTEEN             83   100.000000
44  OFF_DRIB_COLLEGE_BREAK_RIGHT             83   100.000000
32      SPOT_COLLEGE_BREAK_RIGHT             83   100.000000
31          SPOT_COLLEGE_TOP_KEY             83   100.000000
33     SPOT_COLLEGE_CORNER_RIGHT             83   100.000000
46               ON_MOVE_COLLEGE             13    15.662651
42   OFF_DRIB_COLLEGE_BREAK_LEFT             11    13.253012
29      SPOT_COLLEGE_CORNER_LEFT             11    13.253012
21    MODIFIED_LANE_AGILITY_TIME              7     8.433735
20             LANE_AGILITY_TIME              6     7.228916
19             MAX_VERTICAL_LEAP              6     7.228916
18        STANDING_VERTICAL_LEAP              6     7.228916
22          THREE_QUARTER_SPRINT              6     7.228916
14          STANDING_REACH_FT_IN              0     0.000000
12                WINGSPAN_FT_IN              0     0.000000
11                      WINGSPAN              0     0.000000
10                        WEIGHT              0     0.000000
13                STANDING_REACH              0     0.000000
5                       POSITION              0     0.000000
6                HEIGHT_WO_SHOES              0     0.000000
2                     FIRST_NAME              0     0.000000
1                      PLAYER_ID              0     0.000000
4                    PLAYER_NAME              0     0.000000
3                      LAST_NAME              0     0.000000
0                         SEASON              0     0.000000
7          HEIGHT_WO_SHOES_FT_IN              0     0.000000
17                    HAND_WIDTH              0     0.000000
16                   HAND_LENGTH              0     0.000000

In [5]:
# Filter columns with missing_pct <= 50%
cols_to_keep = missing_df[missing_df['missing_pct'] < 50]['column'].tolist()
pd_data_clean = pd_data[cols_to_keep]

print(f"Kept {len(cols_to_keep)} columns, dropped {len(pd_data.columns) - len(cols_to_keep)} columns")
print(f"Original shape: {pd_data.shape}")
print(f"New shape: {pd_data_clean.shape}")

Kept 23 columns, dropped 24 columns
Original shape: (83, 47)
New shape: (83, 23)

In [ ]:
#pd_data_clean.head()
pd_data_clean.columns

Index(['ON_MOVE_COLLEGE', 'OFF_DRIB_COLLEGE_BREAK_LEFT',
       'SPOT_COLLEGE_CORNER_LEFT', 'MODIFIED_LANE_AGILITY_TIME',
       'LANE_AGILITY_TIME', 'MAX_VERTICAL_LEAP', 'STANDING_VERTICAL_LEAP',
       'THREE_QUARTER_SPRINT', 'STANDING_REACH_FT_IN', 'WINGSPAN_FT_IN',
       'WINGSPAN', 'WEIGHT', 'STANDING_REACH', 'POSITION', 'HEIGHT_WO_SHOES',
       'FIRST_NAME', 'PLAYER_ID', 'PLAYER_NAME', 'LAST_NAME', 'SEASON',
       'HEIGHT_WO_SHOES_FT_IN', 'HAND_WIDTH', 'HAND_LENGTH'],
      dtype='str')

In [10]:
cols_to_keep_two = [ 'PLAYER_ID', 'LANE_AGILITY_TIME', 'MAX_VERTICAL_LEAP', 'STANDING_VERTICAL_LEAP',
       'THREE_QUARTER_SPRINT', 'STANDING_REACH_FT_IN', 'WINGSPAN_FT_IN',
         'WEIGHT', 'POSITION', 
       'FIRST_NAME', 'LAST_NAME', 'SEASON',
       'HEIGHT_WO_SHOES_FT_IN', 'HAND_WIDTH', 'HAND_LENGTH']
pd_data_final = pd_data_clean[cols_to_keep_two]
pd_data_final.head()

,PLAYER_ID,LANE_AGILITY_TIME,MAX_VERTICAL_LEAP,STANDING_VERTICAL_LEAP,THREE_QUARTER_SPRINT,STANDING_REACH_FT_IN,WINGSPAN_FT_IN,WEIGHT,POSITION,FIRST_NAME,LAST_NAME,SEASON,HEIGHT_WO_SHOES_FT_IN,HAND_WIDTH,HAND_LENGTH
0,1642369,11.77,34.5,27.0,3.21,8' 10.50'',7' 0.75'',227.80,SF,Michael,Ajayi,2024,6' 5.75'',9.75,9.50
1,1642351,11.78,31.0,26.5,3.38,8' 10.5'',6' 7.5'',213.8,SF,Melvin,Ajinca,2024,6' 7.25'',9.75,8.50
2,1641725,11.37,32.0,26.5,3.21,8' 5.50'',6' 10.50'',187.00,SG,Trey,Alexander,2024,6' 3.25'',10.00,8.75
3,1641891,10.94,35.0,28.0,3.11,9' 2.00'',7' 1.00'',219.60,C,Izan,Almansa,2024,6' 9.25'',9.25,9.25
4,1641736,10.86,36.5,30.0,2.94,8' 4.00'',6' 6.50'',196.44,PG,Reece,Beekman,2024,6' 1.25'',9.00,8.50